bucket            = "<your yandex cloud backend "s3" / bucket>"
access_key        = "<your yandex cloud backend "s3" / access_key>"
secret_key        = "<your yandex cloud backend "s3" / secret_key>"
dynamodb_endpoint = "https://docapi.serverless.yandexcloud.net/ru-central1/b1gp6h932kfsctjqn852/etnbgbenlg0fppu43kpr"
dynamodb_table    = "<your yandex cloud ydb document_api_endpoint"
